#ifndef OPENGL_TYPE_HPP
#define OPENGL_TYPE_HPP

#include <sstream>
#include <string>

#include <glad/gl.h>

namespace opengl {

enum Type {
  BOOL = GL_BOOL,
  BOOL_VEC2 = GL_BOOL_VEC2,
  BOOL_VEC3 = GL_BOOL_VEC3,
  BOOL_VEC4 = GL_BOOL_VEC4,
  BYTE = GL_BYTE,
  DOUBLE = GL_DOUBLE,
  DOUBLE_MAT2 = GL_DOUBLE_MAT2,
  DOUBLE_MAT2x3 = GL_DOUBLE_MAT2x3,
  DOUBLE_MAT2x4 = GL_DOUBLE_MAT2x4,
  DOUBLE_MAT3 = GL_DOUBLE_MAT3,
  DOUBLE_MAT3x2 = GL_DOUBLE_MAT3x2,
  DOUBLE_MAT3x4 = GL_DOUBLE_MAT3x4,
  DOUBLE_MAT4 = GL_DOUBLE_MAT4,
  DOUBLE_MAT4x2 = GL_DOUBLE_MAT4x2,
  DOUBLE_MAT4x3 = GL_DOUBLE_MAT4x3,
  DOUBLE_VEC2 = GL_DOUBLE_VEC2,
  DOUBLE_VEC3 = GL_DOUBLE_VEC3,
  DOUBLE_VEC4 = GL_DOUBLE_VEC4,
  FIXED = GL_FIXED,
  FLOAT = GL_FLOAT,
  FLOAT_MAT2 = GL_FLOAT_MAT2,
  FLOAT_MAT2x3 = GL_FLOAT_MAT2x3,
  FLOAT_MAT2x4 = GL_FLOAT_MAT2x4,
  FLOAT_MAT3 = GL_FLOAT_MAT3,
  FLOAT_MAT3x2 = GL_FLOAT_MAT3x2,
  FLOAT_MAT3x4 = GL_FLOAT_MAT3x4,
  FLOAT_MAT4 = GL_FLOAT_MAT4,
  FLOAT_MAT4x2 = GL_FLOAT_MAT4x2,
  FLOAT_MAT4x3 = GL_FLOAT_MAT4x3,
  FLOAT_VEC2 = GL_FLOAT_VEC2,
  FLOAT_VEC3 = GL_FLOAT_VEC3,
  FLOAT_VEC4 = GL_FLOAT_VEC4,
  HALF_FLOAT = GL_HALF_FLOAT,
  INT = GL_INT,
  INT_VEC2 = GL_INT_VEC2,
  INT_VEC3 = GL_INT_VEC3,
  INT_VEC4 = GL_INT_VEC4,
  SAMPLER_1D = GL_SAMPLER_1D,
  SAMPLER_1D_ARRAY = GL_SAMPLER_1D_ARRAY,
  SAMPLER_2D = GL_SAMPLER_2D,
  SAMPLER_2D_ARRAY = GL_SAMPLER_2D_ARRAY,
  SAMPLER_3D = GL_SAMPLER_3D,
  SHORT = GL_SHORT,
  UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
  UNSIGNED_INT = GL_UNSIGNED_INT,
  UNSIGNED_INT_VEC2 = GL_UNSIGNED_INT_VEC2,
  UNSIGNED_INT_VEC3 = GL_UNSIGNED_INT_VEC3,
  UNSIGNED_INT_VEC4 = GL_UNSIGNED_INT_VEC4,
  UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
};

std::string to_string(const Type& type) noexcept;
}
#endif
